### ISSUE TITLE
Add acceptance tests with Capybara and test bot.

### ISSUE THREAD

**Issue by alanvardy** [alanvardy/alanvardy#407]
I have added effective test bot which is a creation of Matt Riemer of Code and Effect fame.

You can use the effective test bot DSL: https://github.com/code-and-effect/effective_test_bot
And the Capybara DSL which it is built on. https://rubydoc.info/github/teamcapybara/capybara/master#the-dsl

Every time a test fails it creates a screenshot (the link to it will be in the console). When I am writing the tests I like to write the last line as `assert_content 'asidhiudhsf'` to make it fail the last step and show me a screenshot.

You can add tests to the test/system/ folder and run the system tests using `rails test:system`

I have added a few test lines already to give you an example. Don't forget that acceptance tests are the first to fail when something changes, so attempt to confirm as much as possible without being too fine grained about it :)

And see if you can test my contact form without sending me an email every time :)
(Hint: have the model only do the mailgun send in production, and skip the send in test mode after checking validations).

Bombard me with questions and have fun!

**Comment by alanvardy** [comment]
Should I close this @TheWillGabriel , or do you have more in mind?

**Comment by TheWillGabriel** [comment]
I was thinking on a few more, but most of the functionality I was thinking of is already covered by unit tests (or it's admin activity which probably isn't the best candidate for acceptance tests anyway). I think we're probably good for now unless you can think of something that's sorely missing.
